<font style="line-height:16px;font-size:12px;" face="Arial, Verdana, sans-serif" color="#3e3e3e">
    <b>Olá <?=$nome?>,</b><br>
    <p>
        Recebemos seu contato feito em <b><?=date("d/m/Y")?></b> às <b><?=date("H:i")?>.</b>
    </p>
    <p>A partir de agora, vamos analisar sua mensagem e entraremos novamente em contato. Sua solicitação, opinião e comentários é a principal fonte de informação para evoluirmos sempre, por isso daremos o máximo para atendê-lo o mais rápido possível. </p>
    
    <p><b>Origem do contato</b><br>
        Esta mensagem foi enviada partindo do endereço <b><?=$ip?></b> em <b><?=date("d/m/Y")?></b> às <b><?=date("H:i:s")?></b>.
    </p>
    <p>
        <b>Dados fornecidos</b><br>
        <b>Nome:    </b> <?=$nome?><br>
        <b>E-mail:  </b> <?=$email?><br>
        <b>Telefone:</b> <?=$telefone?><br>
        <b>assunto: </b> <?=$assunto?><br>
    </p>
    <div align="center">
        <table width="85%">
            <tbody>
                <tr width="100%" bgcolor="#cccccc">
                    <td style="padding-left:10px;"><b>Mensagem</b></td>
                </tr>
                <tr width="100%" bgcolor="#eeeeee">
                    <td style="padding:10px;">
                        <p><?=nl2br($mensagem)?></p>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="clear"></div>
    <p>Pedimos que aguarde, em breve enviaremos um novo e-mail respondendo seu contato ou se necessário, poderemos ligar diretamente para você.</p><br>
    <b>Obrigado pela confiança!</b>
</font>